# Generated by Django 2.2.3 on 2020-02-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
    ]
