# Generated by Django 2.2.3 on 2020-02-13 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0005_auto_20200212_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('edicion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('referencia', models.CharField(max_length=20, unique=True, verbose_name='Referencia')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
                ('foto', models.ImageField(upload_to=inventario.models.custom_upload_to_producto, verbose_name='Foto')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Marca', verbose_name='Marca')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.UnidadMedida', verbose_name='Unidad de medida')),
                ('user_create', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_update', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creacion'],
            },
        ),
    ]
