# Generated by Django 2.2.3 on 2020-02-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
