# Generated by Django 2.2.3 on 2020-02-16 15:12

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20200212_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=inventario.models.custom_upload_to_producto, verbose_name='Foto'),
        ),
    ]
