# Generated by Django 2.2.3 on 2020-01-25 00:52

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200123_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to=registration.models.custom_upload_to_user, verbose_name='Foto'),
        ),
    ]
