# Generated by Django 2.2.3 on 2020-02-09 16:25

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-creacion'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='cedula',
            field=models.CharField(default=1, max_length=20, validators=[core.validators.validate_only_numbers], verbose_name='Cedula del representante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=20, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='Inactiva'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Nit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.CharField(default=1, max_length=20, validators=[core.validators.validate_only_letters], verbose_name='Representante Legal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=20, null=True, validators=[core.validators.validate_only_numbers], verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user_create',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user_update',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='edicion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
