# Generated by Django 2.2.3 on 2020-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20200125_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
