# Generated by Django 2.2.3 on 2020-01-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20200127_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Seleccionado'),
        ),
    ]
