# Generated by Django 2.2.3 on 2020-01-31 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='selected',
        ),
    ]
